[package]
name = "puppydrive"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
wgui = { git = "https://github.com/J45k4/wgui.git", rev = "351ac73625aeb31ca574a85c0577ae21d6bca501" }